# For more details on the format and content:
# https://github.com/robocorp/rcc/blob/master/docs/recipes.md#what-is-in-condayaml
# Tip: Adding a link to the release notes of the packages helps maintenance and security.

channels:
  - conda-forge

dependencies:
  - python=3.10.12                # https://pyreadiness.org/3.10
  - pip=23.2.1                    # https://pip.pypa.io/en/stable/news
  - robocorp-truststore=0.8.0     # https://pypi.org/project/robocorp-truststore/
  - pip:
    - robocorp==2.0.1             # https://pypi.org/project/robocorp
    - robocorp-browser==2.3.3     # https://pypi.org/project/robocorp-browser
    - rpaframework==28.6.2
    - robotframework==6.1.1
    - selenium==4.15.2